const express = require("express");
const router = express.Router();
const mainRoute = require("./main.routes");
const loginRoute = require("./login.routes");
const productsRoute = require("./products.routes");
const uploadImage = require("./upload.routes");
const authRoutes = require("./auth.routes");
const managePageARoutes = require("./managePageA.routes");
const checkoutRoutes = require("./checkout.routes");
const paymentRoutes = require("./payment.routes");
const orderRoutes = require("./orderDetail.routes");
const trackingRoutes = require("./tracking.routes");
const categoriesRoutes = require("./categories.routes");
const userInfoRoutes = require("./userInfo.routes");
const changePasswordRoutes = require("./changPassword.routes");

router.use("/", mainRoute);
router.use("/login", loginRoute);
router.use("/products", productsRoute);
router.use("/upload", uploadImage);
router.use("/auth", authRoutes);
router.use("/manage-page-a", managePageARoutes);
router.use("/checkout", checkoutRoutes);
router.use("/payment", paymentRoutes);
router.use("/orderDetail", orderRoutes);
router.use("/tracking", trackingRoutes);
router.use("/categories", categoriesRoutes);
router.use("/userInfo", userInfoRoutes);
router.use("/changePassword", changePasswordRoutes);
module.exports = router;
